    version: '3.8'
    services:
      gatsby:
        build: ./app/
        ports:
          - "8000:8000"
        volumes:
          - ./app:/app/
          - gatsby_node_mods:/app/node_modules
        env_file:
          - ./app/.env
       
    volumes:
      gatsby_node_mods: